In [ ]:
!pip install -q chromadb sentence-transformers requests \ beautifulsoup4 rank_bm25 transformers datasets \ scikit-learn pdfplumber Pillow accelerate
!conda install -c conda-forge tesseract -y

In [ ]:
!pip install torch==2.6.0 torchvision torchaudio

Collecting torch==2.6.0
  Downloading torch-2.6.0-cp312-cp312-manylinux1_x86_64.whl.metadata (28 kB)
Collecting torchvision
  Downloading torchvision-0.26.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting torchaudio
  Downloading torchaudio-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (4.15.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (3.6.1)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (3.1.6)
Requirement already satisfied: fsspec in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (2026.2.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (9.1.0.70)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch==2.6.0)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch==2.6.0)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch==2.6.0)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch==2.6.0)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch==2.6.0)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch==2.6.0)
  Downloading nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (2.21.5)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.2.0 (from torch==2.6.0)
  Downloading triton-3.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (80.9.0)
Requirement already satisfied: sympy==1.13.1 in /opt/conda/lib/python3.12/site-packages (from torch==2.6.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy==1.13.1->torch==2.6.0) (1.3.0)
Requirement already satisfied: numpy in /opt/conda/lib/python3.12/site-packages (from torchvision) (2.4.4)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision
  Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
  Downloading torchvision-0.24.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
  Downloading torchvision-0.23.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
  Downloading torchvision-0.22.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
  Downloading torchvision-0.22.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
  Downloading torchvision-0.21.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /opt/conda/lib/python3.12/site-packages (from torchvision) (12.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2->torch==2.6.0) (3.0.3)
Downloading torch-2.6.0-cp312-cp312-manylinux1_x86_64.whl (766.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.6/766.6 MB 117.3 MB/s  0:00:050:00:0100:01
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 112.7 MB/s  0:00:030:00:0100:01
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 236.0 MB/s  0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 59.5 MB/s  0:00:00m0:00:0100:01
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 138.0 MB/s  0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 104.1 MB/s  0:00:020:00:0100:01
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 150.4 MB/s  0:00:00 eta 0:00:01
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 169.7 MB/s  0:00:000:00:0100:01
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 132.5 MB/s  0:00:010:00:0100:01
Downloading nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl (150.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 110.0 MB/s  0:00:010:00:0100:01
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 79.7 MB/s  0:00:00 eta 0:00:01
Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
Downloading triton-3.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (253.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.2/253.2 MB 97.5 MB/s  0:00:02m0:00:0100:01
Downloading torchvision-0.21.0-cp312-cp312-manylinux1_x86_64.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 67.2 MB/s  0:00:00
Downloading torchaudio-2.11.0-cp312-cp312-manylinux_2_28_x86_64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 183.8 MB/s  0:00:00
Installing collected packages: triton, torchaudio, nvidia-cusparselt-cu12, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cusolver-cu12, torch, torchvision
  Attempting uninstall: triton
    Found existing installation: triton 3.1.0
    Uninstalling triton-3.1.0:
      Successfully uninstalled triton-3.1.0
  Attempting uninstall: nvidia-nvtx-cu12━━━━━━━━━━━━━━━━━━━━━━━━━━  2/15 [nvidia-cusparselt-cu12]
    Found existing installation: nvidia-nvtx-cu12 12.1.105━━━━  2/15 [nvidia-cusparselt-cu12]
    Uninstalling nvidia-nvtx-cu12-12.1.105:━━━━━━━━━━━━━━━━━━━  2/15 [nvidia-cusparselt-cu12]
      Successfully uninstalled nvidia-nvtx-cu12-12.1.105━━━━━━  2/15 [nvidia-cusparselt-cu12]
  Attempting uninstall: nvidia-nvjitlink-cu12━━━━━━━━━━━━━━━━━  2/15 [nvidia-cusparselt-cu12]
    Found existing installation: nvidia-nvjitlink-cu12 12.9.86  2/15 [nvidia-cusparselt-cu12]
    Uninstalling nvidia-nvjitlink-cu12-12.9.86:━━━━━━━━━━━━━━━  2/15 [nvidia-cusparselt-cu12]
      Successfully uninstalled nvidia-nvjitlink-cu12-12.9.86━━  2/15 [nvidia-cusparselt-cu12]
  Attempting uninstall: nvidia-curand-cu12━━━━━━━━━━━━━━━━━━━━━━━━  4/15 [nvidia-nvjitlink-cu12]
    Found existing installation: nvidia-curand-cu12 10.3.2.106━━━━  5/15 [nvidia-curand-cu12]
    Uninstalling nvidia-curand-cu12-10.3.2.106:━━━━━━━━━━━━━━━  5/15 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-curand-cu12-10.3.2.106━━  5/15 [nvidia-curand-cu12]
  Attempting uninstall: nvidia-cufft-cu12━━━━━━━━━━━━━━━━━━━━━━━━━  5/15 [nvidia-curand-cu12]
    Found existing installation: nvidia-cufft-cu12 11.0.2.54━━  5/15 [nvidia-curand-cu12]
    Uninstalling nvidia-cufft-cu12-11.0.2.54:━━━━━━━━━━━━━━━━━  5/15 [nvidia-curand-cu12]
      Successfully uninstalled nvidia-cufft-cu12-11.0.2.54━━━━━━━━  6/15 [nvidia-cufft-cu12]
  Attempting uninstall: nvidia-cuda-runtime-cu12━━━━━━━━━━━━━━━━━━  6/15 [nvidia-cufft-cu12]
    Found existing installation: nvidia-cuda-runtime-cu12 12.1.105  7/15 [nvidia-cuda-runtime-cu12]
    Uninstalling nvidia-cuda-runtime-cu12-12.1.105:━━━━━━━━━━━  7/15 [nvidia-cuda-runtime-cu12]
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.1.1050m  7/15 [nvidia-cuda-runtime-cu12]
  Attempting uninstall: nvidia-cuda-nvrtc-cu12━━━━━━━━━━━━━━━━━━━━  7/15 [nvidia-cuda-runtime-cu12]
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.1.1050m  7/15 [nvidia-cuda-runtime-cu12]
    Uninstalling nvidia-cuda-nvrtc-cu12-12.1.105:━━━━━━━━━━━━━  7/15 [nvidia-cuda-runtime-cu12]
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.1.105  7/15 [nvidia-cuda-runtime-cu12]
  Attempting uninstall: nvidia-cuda-cupti-cu120m━━━━━━━━━━━━━━━━━━  8/15 [nvidia-cuda-nvrtc-cu12]
    Found existing installation: nvidia-cuda-cupti-cu12 12.1.1050m  8/15 [nvidia-cuda-nvrtc-cu12]
    Uninstalling nvidia-cuda-cupti-cu12-12.1.105:━━━━━━━━━━━━━  8/15 [nvidia-cuda-nvrtc-cu12]
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.1.105  8/15 [nvidia-cuda-nvrtc-cu12]
  Attempting uninstall: nvidia-cublas-cu12━━━━━━━━━━━━━━━  9/15 [nvidia-cuda-cupti-cu12]
    Found existing installation: nvidia-cublas-cu12 12.1.3.1━━  9/15 [nvidia-cuda-cupti-cu12]
    Uninstalling nvidia-cublas-cu12-12.1.3.1:0m━━━━━━━━━━━━━━━  9/15 [nvidia-cuda-cupti-cu12]
      Successfully uninstalled nvidia-cublas-cu12-12.1.3.1━━━━  9/15 [nvidia-cuda-cupti-cu12]
  Attempting uninstall: nvidia-cusparse-cu12━━━━━━━━━━━━━ 10/15 [nvidia-cublas-cu12]
    Found existing installation: nvidia-cusparse-cu12 12.1.0.1060m 10/15 [nvidia-cublas-cu12]
    Uninstalling nvidia-cusparse-cu12-12.1.0.106:━━━━━━━━━━━━━ 10/15 [nvidia-cublas-cu12]
      Successfully uninstalled nvidia-cusparse-cu12-12.1.0.106 10/15 [nvidia-cublas-cu12]
  Attempting uninstall: nvidia-cusolver-cu120m╺━━━━━━━━━━ 11/15 [nvidia-cusparse-cu12]
    Found existing installation: nvidia-cusolver-cu12 11.4.5.1070m 11/15 [nvidia-cusparse-cu12]
    Uninstalling nvidia-cusolver-cu12-11.4.5.107:╺━━━━━━━ 12/15 [nvidia-cusolver-cu12]
      Successfully uninstalled nvidia-cusolver-cu12-11.4.5.107 12/15 [nvidia-cusolver-cu12]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [torchvision] [torchvision]ver-cu12]
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-cusparselt-cu12-0.6.2 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 torch-2.6.0 torchaudio-2.11.0 torchvision-0.21.0 triton-3.2.0

In [ ]:
# 커널 재시작 필수 !!! 아래 주석처럼 나와야 함.
import torch
print(torch.__version__)  # 2.6.x+cu
print(torch.cuda.is_available())      # True
print(torch.cuda.get_device_name(0))  # NVIDIA RTX A5000

2.6.0+cu124

In [ ]:
# train 파일 읽기
exec(open('train.py').read())

train_colab.py 로드 완료.
  대상 연도: 2026
사용 가능한 함수:
  notices = crawl_all()
  notices = load_notices_cache()  ← 캐시 재사용
  qwen = load_qwen_model()                      ← Qwen2.5-7B 로드
  notices = crawl_all(qwen_pipe=qwen)           ← 크롤링 + QA 동시 생성
  finetune_all(notices)                         ← QA 자동 재사용
  finetune_embedding(notices, qwen_pipe=qwen)   ← 임베딩만
  finetune_classify(notices)                    ← 분류만
  evaluate_embedding(notices)      ← 파인튜닝 전후 Recall@K, MRR 비교
  save_models()

In [ ]:
# 크롤링 (OCR, PDF 포함) 및 QA 생성(공지당 3문항) - 이미 QA 파일이 존재하다면 스킵하세요.
qwen = load_qwen_model()
notices = crawl_all(qwen_pipe=qwen)

  🤖 Qwen2.5-7B-Instruct 로드 중... (최초 1회, 수 분 소요)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 339/339 [00:06<00:00, 56.30it/s]

  ✅ Qwen 모델 로드 완료
📋 2026년 공지 수집 + QA 생성 시작 (Qwen2.5-7B 사용)...
  페이지 1: 20건 (누적 20건)
  페이지 2: 20건 (누적 40건)
  페이지 3: 20건 (누적 60건)
  페이지 4: 20건 (누적 80건)
  페이지 5: 20건 (누적 100건)
  페이지 6: 20건 (누적 120건)
  페이지 7: 20건 (누적 140건)
  페이지 8: 20건 (누적 160건)
  페이지 9: 20건 (누적 180건)
  페이지 10: 20건 (누적 200건)
  페이지 11: 20건 (누적 220건)
  페이지 12: 20건 (누적 240건)
  페이지 13: 20건 (누적 260건)
  페이지 14: 20건 (누적 280건)
  페이지 15: 20건 (누적 300건)
  페이지 16: 20건 (누적 320건)
  페이지 17: 20건 (누적 340건)
  페이지 18: 20건 (누적 360건)
  페이지 19: 20건 (누적 380건)
  페이지 20: 20건 (누적 400건)
  페이지 21: 20건 (누적 420건)
  페이지 22: 20건 (누적 440건)
  페이지 23: 20건 (누적 460건)
  페이지 24: 20건 (누적 480건)
  페이지 25: 2건 (누적 482건)
  → 본문 크롤링 시작...

Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

  [1/482] [비교과] [취업행사] 제4회 로봇채용위크 in 용산( 4/29 10:00 )

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [2/482] [수업] 2026학년도 1학기 중간고사 기간 학술정보관 운영시간 연장 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [3/482] [비교과] [교육] [가천대 대플] 거점형 [온라인 실시간] 컴활 자격 대비 프로그 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [4/482] [장학] 국가장학금 2026학년도 국가우수장학금(인문/예술) 신규장학생 선발 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [5/482] [비교과] 2026학년도 1학기 HS CREW 재학생 소모임 지원 프로그램 신청 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [6/482] [장학] [긴급] 외부인 교내 무단출입 및 사칭 관련 주의 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [7/482] [수업] [교육] [경기도 거주 미취업자 ] 성남시 시스템반도체 설계(팹리스) 아 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [8/482] [취업] 채용정보 [추천채용](주)디아이(삼성전자협력사) 어플리케이션 엔지니어(고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [9/482] [기타] [창업멘토링] 2026-1학기 한성 CEO 발굴 창업멘토링 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [10/482] [수업] 채용정보 [채용] 한성대학교 지식서비스&컨설팅대학원 행정연구원(사무직)  → QA 3개

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [11/482] [취업] 채용정보 [일반채용] [금융공공기관]울산신용보증재단 일반직6급 (~4/2 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fca8ac9b060>
  [12/482] [수업] [문래청소년센터] 2026년 시립문래청소년센터 진로 강사 양성과정 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [13/482] [비교과] 채용정보 [추천채용/서류면제] 컨설팅세일즈(운전면허 소지 필수) 신입(~ → QA 3개
    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fca8ac9af20>

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [14/482] [기타] [(사)한국교육연구소] AI기반 에너지 컨설턴트 양성과정 교육생 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [15/482] [수업] [채용] 산업시스템공학부 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [16/482] [수업] [채용] IT인프라팀 상상관 기자재실 야간 조교 / IT인프라팀 행사공간 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [17/482] [취업] 인턴쉽 ★[고노부 미래내일일경험]삼덕회계법인, 롯데의왕점_[사무직] 일경 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [18/482] [장학] [SW중심] 제25회 TOPCIT(소프트웨어 역량검정 시험) 정기평가 시 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [19/482] [장학] 한성대 재학생 전용 Adobe 공동구매 특별 프로모션 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [20/482] [취업] 채용정보 [추천채용/서류가산] 영림그룹 영업부, 영업관리부 각 신입(~4 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fca89281530>
  [21/482] [취업] [(재)장애인기업종합지원센터] 「2026년 장애인기업종합지원센터 청년기자 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [22/482] [장학] AI·Adobe 구독 지원(교육장학금) 시행 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [23/482] [비교과] [자율전공설계지원센터] HS메이저노트(전공탐색노트) 파일 및 사용안내 영 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [24/482] [장학] 2026학년도 1학기 전공(트랙)연계 협업형 진로·취업멘토링 참가자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [25/482] [취업] 채용정보 [추천채용] (주)파트론(삼성전자협력사)_구매관리직(군필자) 신 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [26/482] [수업] [채용] 국제학생입학지원센터 계약직원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [27/482] [수업] [채용] 국제교류지원팀 계약직원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [28/482] [기타] 공모전 등 2025 AI를 활용한 장애인식개선 동화 공모전 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [29/482] [취업] [화성시 거주자] 2026년 미래기술학교 제약바이오 전문가 양성과정 교육 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [30/482] [취업] 채용정보 [한화손보] 2026 상반기 신입사원 모집 (~4/20) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [31/482] [장학] 2026학년도 1학기 하계 영어권 온라인 어학연수 참가학생 선발안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [32/482] [비교과] [취업박람회]2026 제1차 [KB굿잡]우수기업 취업박람회(4/27 10 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [33/482] [장학] 학자금대출 2026년 경기도 학자금대출 장기연체자 신용회복 지원 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [34/482] [비교과] [자율전공설계지원센터] 2026-1학기 전공설계지도(AA) 상담 OPEN → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [35/482] [장학] [생성형 AI 활용 경진대회] 제1회 한성 <AX프런티어> 챌린지 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [36/482] [기타] HSU AI HUB(멀티 LLM 생성형 AI 플랫폼) 정식 오픈 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [37/482] [비교과] 강소기업채용 ★[26.04.01]강소 및 교내 추천채용 리스트★ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [38/482] [장학] [채용] 학생복지팀 계약직원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [39/482] [장학] 교외장학금 2026년 (사)유쾌한반란 카카오뱅크 스칼라십 장학생 모집 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [40/482] [장학] 2026학년도 1학기 고시반 입반생 모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [41/482] [수업] [채용] 언어교육센터 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [42/482] [취업] 환동해 글로컬 연합 아카데미 [2026년 이차전지 취업준비형 교육과정 4 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [43/482] [장학] 채용정보 [NH농협손해보험] 2026년 상반기 NH농협손해보험 신규직원  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [44/482] [취업] 채용정보 [채용][인테그리스코리아] 2026 글로벌 리더-엔지니어 직무  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [45/482] [수업] [직원채용]글로컬협력처 언어교육센터 행정직원(임시직) 채용공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [46/482] [비교과] [ESG센터] ESG 탄소중립 실천 서포터즈 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [47/482] [수업] 4.12(일) 한국어능력시험(TOPIK) 교내 시행에 따른 협조요청 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [48/482] [수업] 서울RISE사업단 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [49/482] [취업] 채용정보 [아워홈] 2026 아워홈 식재영업 채용 전환형 인턴 채용(~4 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [50/482] [비교과] 인턴쉽 ★[고노부 미래내일일경험] 한국콜마, 컴포트_일경험 8주 인턴(~ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [51/482] [수업] 채용정보 [추천채용/서류가산]스킨이데아_ 상품기획 인턴(평가 통한 정규) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [52/482] [수업] 2026학년도 1학기 다전공(복수/부전공, 연계전공,제3트랙, MD과정) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [53/482] [장학] 교외장학금 2026년 (재)인천인재평생교육진흥원 인천 청년 해외배낭연수  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [54/482] [비교과] 제1회 한성 <AX프론티어> 챌린지 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [55/482] [장학] 교외장학금 2026년 (재)서울장학재단 청춘Start 장학금 장학생 선발 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [56/482] [비교과] 채용정보 [채용][무신사리테일서비스] MMC - 무신사 글로벌 경영자 후 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [57/482] [장학] 교외장학금 2026년 (재)우양재단 기명·기타 장학생 모집 안내(4/9  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [58/482] [장학] 교외장학금 2026년 국회기후변화포럼 기후변화 장학생 선발 안내(5/2  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [59/482] [기타] [산학연구기획팀] 한국연구재단 2026 연구윤리 현장투어 안내 → QA 3개
    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc996c6b970>
  [60/482] [기타] [시립마포청소년센터] 2026년 장애·비장애 청소년 통합활동 '라온:Ro

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [61/482] [장학] 교외장학금 2026년도 (재)전북특별자치도평생교육장학진흥원 향토인재 장학 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [62/482] [장학] 교외장학금 2026년도 (재)울산남구장학재단 우듬지 인재 키움 장학생 모 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [63/482] [비교과] [SW중심] 2026학년도 SW중심대학 「에세이 공모전」 안내(재공지) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [64/482] [수업] [채용]한성대학교 지식서비스&컨설팅대학원 스마트융합컨설팅학과 행정연구원  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [65/482] [취업] [어플라이드 머티어리얼즈 코리아] [반도체 디스플레이장비기업]신입/인턴  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [66/482] [수업] [채용] 사회과학대학 교학팀 직원(계약직) 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [67/482] [장학] 2027학년도 학석사연계과정 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [68/482] [취업] 채용정보 [추천채용] 영림그룹 인천 본사 [관리부 회계총무/실 운전가능자 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [69/482] [장학] 국가장학금 2026년 푸른등대 삼성기부장학금 신규장학생 선발 안내(4/7 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [70/482] [비교과] 채용정보 [채용][이수그룹] 신입사원 공개채용(~4/14 10:00) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [71/482] [비교과] [채용] 한성대학교 지역평생교육지원단 평생교육통합지원센터 교육연구교수 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [72/482] [비교과] 강소기업채용 ★[26.03.25]강소 및 교내 추천채용 리스트★ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [73/482] [취업] 채용정보 [채용][KT&G] 2026년 상반기 KT&G 신입/경력사원 ( → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [74/482] [장학] 교외장학금 2026년도 상반기 (재)인천인재평생교육진흥원 장학생 선발 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [75/482] [장학] 교외장학금 2026년 상반기 (재)춘천인재육성장학재단 봄내장학생 선발 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [76/482] [장학] 2026학년도 2학기 중화권 파견 교환학생 선발 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [77/482] [장학] [자율전공설계지원센터] 2026-1학기 트랙 홍보대사 모집 (3.23~4 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [78/482] [취업] [교내 추천채용 활용 가이드] HS대플과 함께하는 ‘추천채용’ 알고 계신 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [79/482] [장학] [교육][모집 안내(국비)] K-디지털 트레이닝 '빅데이터 디지털금융 전 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [80/482] [수업] 채용정보 [추천채용/서류가산] [선배 재직 중] 트루델리(주) [영어 가 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [81/482] [비교과] [한양여대 대플] 외항사 객실승무원 현직자 온라인 특강(~3/26 16: → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [82/482] [취업] 「HSU AI HUB」 생성형 AI 무료제공 및 교육·연구 지원 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [83/482] [비교과] 내일을 여는 상상 Insight 「마스터 클래스」 2회차 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [84/482] [장학] (연장) [창업지원] 2026년 창업기업육성ICC 입주기업 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [85/482] [수업] 학생홍보대사 하랑 24기 최종 선발 결과 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [86/482] [장학] 채용정보 [추천채용/서류면제]송월타올 서울지사 _리테일영업팀[일본어 필수 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [87/482] [비교과] [ESG센터X한국전기안전공사] KESCO ESG 경영 대학생 참여단 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [88/482] [수업] 채용정보 [아모레퍼시픽]2026 상반기 아모레퍼시픽 신입 채용(~4/8) → QA 3개
    ⚠️ OCR 실패 (https://career.hansung.ac.kr/attachment/view/82743): cannot identify image file <_io.BytesIO object at 0x7fca0644f290>
    ⚠️ OCR 실패 (https://career.hansung.ac.kr/attachment/view/82744): cannot identify image file <_io.BytesIO object at 0x7fca063f36a0>

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://career.hansung.ac.kr/attachment/view/82745): cannot identify image file <_io.BytesIO object at 0x7fca063f36a0>
  [89/482] [취업] 채용정보 [채용]2026 에스엘그룹 상반기 신입/경력사원 모집(~4/5) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [90/482] [취업] 인턴쉽 [준정부기관-한국재정정보원] 2026년 제2차 채용(6개월 기간제 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [91/482] [취업] 채용정보 [채용][아워홈]2026 아워홈 식재영업 채용전환형 인턴 채용( → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [92/482] [장학] [국비교육]키움증권 키움 디지털 아카데미 4기생 모집(~4/17) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [93/482] [수업] <HSU AI HUB (멀티 LLM 생성형 AI 플랫폼) 도입 안내> → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [94/482] [취업] 채용정보 [추천채용/서류가산] 2026 토스페이먼츠 Sales Speci → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [95/482] [기타] [긴급공지] 광화문 일대 대규모 행사(BTS공연)관련 안전 유의 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [96/482] [수업] 2026학년도 여름계절학기 희망개설강좌 설문조사(3.23.(월) ~ 4. → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [97/482] [비교과] [교육] 「2026년 뷰티 비즈니스 아카데미」 상반기 교육생 모집(~4/ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc98cdefbf0>
  [98/482] [비교과] [수원시국제교류센터] 대학생 국제교류 서포터즈 "수원시 공공외교단 13기 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc98cdeeb10>
  [99/482] [기타] [성동청소년문화의집] 대학생 서포터즈 신규단원 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [100/482] [장학] 2026학년도 1학기 하계 영어권 단기프로그램 파견학생 선발안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [101/482] [비교과] [HS졸특][ 26.04.01] 26-1 취준특강 1차:면접 필살기(~3 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [102/482] [비교과] [SIMTOS 2026 커리어커넥트 전시회] 채용 박람회 사전 신청(~4 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [103/482] [비교과] 트랙제 소속 학생의 트랙변경에 따른 학점인정 전공과목 전공 인정 신청 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [104/482] [수업] 기존 학부제 학생의 트랙제로 소속변경에 따른 전공학점 인정신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [105/482] [취업] 채용정보 [공공기관채용] 한국연구재단 제1차 정규 연구직/공무직(사무지원 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [106/482] [비교과] [교육][한남대] 2026년 「반도체 공정 입문교육 및 전문가 과정」 신 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [107/482] [취업] 채용정보 [추천채용/서류면제]한샘 대리점 [리하우스 디자이너(기술영업직) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [108/482] [비교과] [한성대학교 방송국 HBS] ✨🎤제48회 낙산가요제 참가자 모집 안내🎤✨ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [109/482] [비교과] [잠실청소년센터] 2026년 학교연계활동단 '잠실지기' 대학생 모집 → QA 2개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [110/482] [수업] [채용] 한성대학교 대학원교학팀 행정연구원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [111/482] [기타] [글로벌원스톱센터] ISIC 국제학생증 인증비 지원행사 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [112/482] [수업] 채용정보 [CJ제일제당] 2026 상반기 식품사업부문 신입사원 모집 (~ → QA 3개

Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [113/482] [취업] 채용정보 [추천채용/서류가산] 법무법인(유한) 태평양 송무/비서/홍보/전 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [114/482] [비교과] 정보 2026 MIT 글로벌 스타트업 워크샵(MIT GSW 2026) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [115/482] [장학] 정보 [서울시] 2026 서울시 빅데이터 활용 경진대회(~5/13 18: → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [116/482] [비교과] 정보 [진주시] 2026 K-기업가정신 창업경진대회(~4/10 16:00 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [117/482] [비교과] 강소기업채용 [26.03.18]강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [118/482] [장학] 2026학년도 1학기 학점포기 신청 안내(14학번 이전 대상) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [119/482] [장학] 교외장학금 2026년 상반기 (재)서울장학재단 서울인재대학장학생 선발 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [120/482] [비교과] 2026학년도 1학기 조기졸업 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [121/482] [취업] 채용정보 [GS칼텍스] 2026년 상반기 GS칼텍스 신입사원 채용 (~3 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [122/482] [취업] 채용정보 2026 상반기 KB국민은행 신입행원 채용 (~3/25 18:0 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [123/482] [수업] 채용정보 [채용]2026 상반기 현대아산 채용연계형[8개 직무] 인턴(1 → QA 2개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [124/482] [취업] 채용정보 [추천채용/서류가산]지큐브스페이스(주)베스트슬립 CX매니저 정규 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [125/482] [수업] 학생홍보대사 하랑 24기 서류심사 결과 및 면접전형 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [126/482] [기타] 2026년도 해외 일경험 온라인 설명회 개최 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [127/482] [수업] 채용정보 [추천채용] (주)웨이비스 모듈개발 부문- 신입 [ RF / 기 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [128/482] [비교과] 2026학년도 1학기 창업동아리(1차) 선발 결과 발표 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [129/482] [취업] 채용정보 [추천채용] [쿠팡로지스틱스서비스] 헬퍼(현장 일용직) 채용 및 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [130/482] [장학] 교외장학금 2026년 (사)맑고 향기롭게 7기 대학 장학생 선발 안내(4 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [131/482] [장학] 학자금대출 2026년 상반기 익산시 대학생 학자금 대출이자 지원 신청 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [132/482] [비교과] 내일을 여는 상상 Insight 「마스터 클래스」 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [133/482] [수업] [조교채용] 한성대학교 글로컬협력처 언어교육센터 한국어과정 조교 채용 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [134/482] [장학] 채용정보 2026 [서한그룹] 신입·경력사원 공개 채용 (~3/30) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [135/482] [장학] 채용정보 [LG유플러스] 2026년 3월 신입채용 (~3/29 23:00 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [136/482] [장학] 2026학년도 2학기 튀르키예 파견 교환학생 선발안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [137/482] [취업] 채용정보 [채용][한화에어로스페이스] 2026 상반기 대규모 신입사원 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [138/482] [장학] [창업지원] 2026년 창업기업육성ICC 입주기업 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [139/482] [비교과] [한성대신문사] 제20회 사진공모전 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [140/482] [수업] 채용정보 [채용][세아베스틸 2026 상반기 세아베스틸 채용(~3/22) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [141/482] [수업] [채용] 한성대학교 서울RISE사업단 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [142/482] [취업] [취업연계 교육] 26년 3,4월 개강 [현대퓨처넷·비스텔리젼스] 채용연 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [143/482] [비교과] [SW중심] 2026학년도 SW중심대학 「에세이 공모전」 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [144/482] [수업] [채용]2026년 SW·AI융합교육센터 계약직원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [145/482] [수업] 채용정보 [추천채용] (주)호룡 중앙연구소 _미래전략 국책과제 수행 및  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [146/482] [취업] 채용정보 [채용][당근] 2026 ML 직군 채용 / 학º석사 신입 &  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [147/482] [장학] 국가장학금 2026년 1학기 국가장학금 신청자 가구원 동의 독려 안내(3 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [148/482] [기타] 학교법인 한성학원 개방감사 후보자 초빙 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [149/482] [비교과] 2026-1학기 글로벌 컨버세이션 파트너 프로그램 참가자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [150/482] [비교과] [외부취준행사][26.04 상생 채용박람회] '사전 ' 취업지원 행사 M → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [151/482] [장학] (한성대 동문 대상) 취업 성공 수기 작성하고 지원금(자문비) 받자! → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [152/482] [기타] 대학일자리플러스센터(3기) 학생 홍보대사 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [153/482] [수업] 2026학년도 1학기 폐강안내 및 폐강강좌 수강신청자 수강정정 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [154/482] [장학] 학자금대출 2026년 상반기 군산시 대학생 학자금 이자 지원사업 안내(3 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [155/482] [장학] 교외장학금 2026년도 (재)대구동구교육재단 장학생 선발 안내(3/27  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [156/482] [취업] 채용정보 [교내 교수님 추천] (주)아이엠탐 BOSS GOLF 브랜드 _ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [157/482] [수업] 잡플래닛(기업정보 플랫폼) 이용 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [158/482] [비교과] 강소기업채용 [26.03.11]강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [159/482] [비교과] 채용정보 [채용][(재)경기도교육연구원]수탁사업 계약직원(연구직, 관리직 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [160/482] [취업] 채용정보 [채용] 삼성중공업 신입 및 인턴 채용(~3/17 17:00) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [161/482] [취업] 인턴쉽 [채용]2026 KB라이프생명 채용연계형 인턴 채용 (~3/20) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [162/482] [장학] 교외장학금 2026년 (재)광진복지재단 미래도약 장학지원 사업 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [163/482] [수업] 2026년 1학기 학생생활상담센터 개인상담&심리검사 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [164/482] [장학] 교외장학금 교외장학금 장학생 신청서·추천서 총장직인 요청에 관한 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [165/482] [취업] 채용정보 [채용]삼성물산 건설부문 '26 상반기 신입사원 모집(~3/17 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [166/482] [수업] 채용정보 [롯데케미칼 첨단소재사업] 2026년 3월 신입사원(일반전형)( → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [167/482] [비교과] [채용] 한성대학교 지역평생교육지원단 평생교육통합지원센터 교육연구교수 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [168/482] [취업] 채용정보 [채용]2026 S-OIL 소매영업직 신입사원 채용(~3/22) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [169/482] [수업] 채용정보 [GS건설] 2026년 상반기 GS건설 신입사원 채용 (~3/2 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [170/482] [비교과] 인턴쉽 [채용][현대카드|현대커머셜] 2026 Internship (~3 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [171/482] [수업] [채용] 2026년 SW중심대학사업단 계약직원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [172/482] [수업] [채용] 산업시스템공학부 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [173/482] [취업] [2026매력일자리xAI 활용 해외바이어 발굴 및 글로벌 마케팅 전문가  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [174/482] [장학] 2026학년도 1학기 수강포기 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [175/482] [비교과] 🚨모집기간 연장🚨[한성대학교 방송국 HBS] 제49기 수습국원 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [176/482] [수업] 재학생 예비군 훈련 참가에 따른 관련 협조 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [177/482] [비교과] [KOICA] 프로젝트 봉사단(7기) 파견 단원 모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [178/482] [장학] 교외장학금 2026년 미래에셋박현주재단 제35기 해외교환 장학생 선발 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [179/482] [비교과] 채용정보 [추천채용/서류가산] (주)알체라 사업운영지원 및 콘텐츠마케터  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [180/482] [장학] 2026학년도 천원의 아침밥 시행 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [181/482] [장학] 교외장학금 2026년 상반기 (재)논산시장학회 학업장려 장학생 선발 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [182/482] [비교과] 인턴쉽 [보령 CHQ] Innovation Accelerator Team → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [183/482] [장학] 국가장학금 26년도 1학기 중소기업 취업연계 장학사업(희망사다리 1유형) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [184/482] [수업] [채용] 산업시스템공학부 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [185/482] [기타] [강북교육복지센터] 대학생 학습멘토 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [186/482] [비교과] [ESG센터] 2026년 3월 성북구 주민자율 대청소 봉사자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [187/482] [취업] 2026학년도 제24기 학생홍보대사 '하랑' 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [188/482] [장학] [모집] 2026-1학기 창업동아리 모집(1차) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [189/482] [기타] 예비군훈련에 참여하는 학생의 학업보장 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [190/482] [기타] 2026년 예비군훈련 일정안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [191/482] [비교과] 2026 상반기(3기) 산업안전상생 일 경험 아카데미 참여학생모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [192/482] [취업] 채용정보 서울특별시 기간제근로자(8개월) (빅데이터 분석요원) (~3/1 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [193/482] [취업] 채용정보 [채용]서울특별시 기간제(6개월) 근로자(통계·데이터 관리요원) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [194/482] [장학] [한국장학재단] 2026년 한국장학재단 대학생 홍보대사 모집 안내(3/1 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [195/482] [기타] [성북구 보건소] 금연클리닉 운영 안내 홍보 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [196/482] [장학] 2025-2학기 한성 앰버서더 참가자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [197/482] [장학] 2025-2학기 한성 글로벌 튜터링 참가자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [198/482] [수업] 제목: [채용] 한성대학교 지식서비스&컨설팅대학원 행정연구원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [199/482] [장학] 국가장학금 2026학년도 1학기 국가우수장학금(인문/예술) 학생 사전신청 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [200/482] [기타] [공지] 교내(우촌관) 유무선 인터넷 및 전산서비스 일시중단 안내(3/4 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [201/482] [장학] 정보 [KOICA] 리턴프로그램 창업팀 모집 (~3/8) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [202/482] [비교과] 강소기업채용 [26.03.04]강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [203/482] [수업] 2026학년도 1학기 조기취업자 중 공결처리(출석인정) 신청 안내(수정) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [204/482] [취업] 채용정보 [롯데그룹] 3·6·9·12 예측가능한 롯데그룹 채용 '3월 공 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [205/482] [수업] 채용정보 [채용][롯데백화점]2026년 상반기 롯데백화점 신입사원 채용  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [206/482] [비교과] 2026학년도 1학기 비교과포인트 신청 및 기간 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [207/482] [비교과] 2026학년도 1학기 K-MOOC 강좌 학점 인정 시행 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [208/482] [취업] 채용정보 [대플 취업 교수님 추천채용] (주)영림원소프트랩 총무(유지보수 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [209/482] [수업] 채용정보 [채용][하나은행] 2026 상반기 신입행원 채용 (~3/16  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [210/482] [취업] [대외활동] 2026년 서울북부 청년기자단(4기) 모집(~3/20) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [211/482] [장학] 국가장학금 2026학년도 1학기 고졸 후학습자 장학금(희망사다리Ⅱ유형)  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [212/482] [수업] 2026-1학기 스마트융합교육센터 서면신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [213/482] [비교과] [LG사이언스파크] 디스커버리투어_전기/전자 신청자 모집(~3/13 14 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [214/482] [비교과] 채용정보 [채용][한화에너지] 2026 상반기 신입사원 공개채용 (~3/ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [215/482] [수업] 채용정보 [채용][LIG] 2026 상반기 LIG 인재영입 (~3/18) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [216/482] [수업] 채용정보 [채용] [하나증권] 2026 상반기 신입사원 채용 (~3/13 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [217/482] [장학] '26년도 전반기 67·68기 학군사관(ROTC) 후보생 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [218/482] [취업] 채용정보 [추천채용] 영림그룹_생산관리부&갤러리 근무 (~3/15) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [219/482] [비교과] 2026학년도 1학기 동아리 & 학습박람회 행사 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [220/482] [기타] [교양영어과정] 2026년 1학기 영어커뮤니케이션 이수 면제 결과 공지 → QA 2개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [221/482] [수업] 2026학년도 1학기 헤이영 전자출결시스템 사용 방법 및 출결 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [222/482] [기타] [홈페이지 전환 안내] → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [223/482] [장학] 국가근로 [양식] 4대보험 가입 아르바이트 근로자 국가근로 참여 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [224/482] [수업] [채용] IT인프라팀 상상관 / 탐구관 기자재실 야간조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [225/482] [비교과] 2026학년도 1학기 편입생 전적대학 학점 신규(재사정) 인정 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [226/482] [취업] 채용정보 [추천채용/서류가점]케이앤유 수입화장품 마케팅 BM(Brand  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [227/482] [장학] 교외장학금 2026년 1학기 선원가족 장학생 모집 안내(4/10 마감) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [228/482] [장학] 국가근로 2026학년도 1학기 국가근로장학금 사전교육자료 첨부 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [229/482] [취업] 채용정보 [추천채용/서류전형면제] 대림바스 영업직 신입 (~3/5) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [230/482] [수업] [채용] 한성대학교 대학원 행정연구원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [231/482] [비교과] 채용정보 [추천채용] 글로벌주방용품 한국본사 플라스틱 용기 신제품 디자인 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [232/482] [장학] 교외장학금 2026년 상반기 (재)울산연구원 장학생 선발 안내(4/3 마 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [233/482] [비교과] 2026학년도 편입생 설명회 자료배포 및 만족도조사 안내 → QA 2개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [234/482] [비교과] 강소기업채용 [26.02.25.] 강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [235/482] [비교과] [RISE사업추진센터] 2026-1학기 예비창업MD · 실전응용창업MD  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [236/482] [수업] [재공고] 한성대학교 교육혁신처 교육혁신지원센터 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [237/482] [비교과] 채용정보 [추천채용] 파수, 스패로우 - 2026년 1차 신입 공개 채용 → QA 3개
    ⚠️ OCR 실패 (https://mail.google.com/mail/u/0?ui=2&ik=d3eba66b4): cannot identify image file <_io.BytesIO object at 0x7fc99834d760>
  [238/482] [기타] 심곡동종합사회복지관 대학생 봉사자 모집

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [239/482] [장학] 국가장학금 2026학년도 1학기 푸른등대 기부장학금 신규장학생 선발 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [240/482] [기타] [2026학년도 신입생 대상] 교양필수교재『사고와 표현』배부 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [241/482] [수업] 2026학년도 신·편입생 반편성고사 연장안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [242/482] [장학] 교외장학금 2026년 MG새마을금고 청년누리 장학생 모집 안내(3/2 마 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [243/482] [장학] 교외장학금 2026년 (재)삼원장학재단 제24기 삼원장학생(시각디자인전공 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [244/482] [비교과] 2026학년도 1학기 국제교류 프로그램 설명회 개최 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [245/482] [기타] 2026학년도 입학식 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [246/482] [비교과] 2026학년도 글로벌버디 5기 모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [247/482] [장학] 2026학년도 HS 학생성공 비교과 교육과정 가이드북 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [248/482] [수업] [상상빌리지]2026학년도 1학기 상상빌리지(행복기숙사) 추가모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [249/482] [장학] 2026-1학기 상상력인재학부 멘토링 프로그램 '상상멘토단' 추가 모집  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [250/482] [수업] 2025학년도 전기 학사학위취득 유예 승인결과 조회 및 승인취소 신청 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [251/482] [장학] 2026학년도 1학기 동소문행복기숙사 상시모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [252/482] [취업] 채용정보 [추천채용] 모두투어네트워크_부문별[영업/상품/지원] 채용연계형 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [253/482] [비교과] 인턴쉽 [추천채용] 글로벌주방용품 한국본사 플라스틱 용기 신제품 디자인  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [254/482] [장학] [ESG센터] 한성대학교 사회봉사단(H.U.V) 9기 신입생 및 재학생  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [255/482] [비교과] 2026-1학기 자기주도 일경험 프로젝트 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [256/482] [수업] 2026학년도 1학기 디자인대학 서면신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [257/482] [장학] 교외장학금 2026학년도 1학기 (재)연재장학재단 31기 장학생 선발 안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [258/482] [기타] 2027학년도 대입전략 '대학생이 알려주는 합격 필승비법' 대학생 멘토  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [259/482] [비교과] [대구광역시]「청년 귀환 채널구축 사업(고향올래)」SNS 서포터즈 1차  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [260/482] [기타] [서울시립일시청소년쉼터] 2026년 자원활동가 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [261/482] [비교과] [RISE사업추진센터] 2026-1학기 예비창업MD · 실전응용창업MD  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [262/482] [장학] 국가장학금 2026학년도 1학기 주거안정장학금 대학 자체 우선지원 및 지 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [263/482] [비교과] [채용] 글로벌원스톱센터 계약직원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [264/482] [수업] [KDT] 빅데이터를 활용한 디지털금융 전문가 과정 5기 모집 (3/20 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [265/482] [기타] [시립마포청소년센터] 2026년 YNBC대학생미디어활동단 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [266/482] [취업] 채용정보 [추천채용] 상상인그룹 채용연계형&체험형 인턴 직무별 (~02/ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [267/482] [수업] 교양교과목 수강신청 수강정원 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [268/482] [비교과] [서울시] 2026 글로벌 SNS 서포터즈 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc9984e6480>
  [269/482] [기타] [수원시립미술관] 대학생 서포터즈 AmS 제8기 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [270/482] [취업] 2025 동계 진로 취업 멘토링 우수 자기 소개서 입상자 발표 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [271/482] [기타] [교육혁신지원센터] 2025학년도 전공교육과정 우수사례 공유 워크숍 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [272/482] [비교과] [용산구진로직업체험지원센터] 2026년 대학교 전공멘토단 'Men:P(멘 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [273/482] [수업] 2026학년도 1학기 신입생 학번 조회 및 주요사항 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [274/482] [장학] 2026학년도 장학제도 개편 및 국가장학금Ⅱ유형 관련 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [275/482] [비교과] [RISE사업추진센터] 서울RISE사업 2026년 창업 아이디어톤 참가자 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [276/482] [비교과] 2026학년도 신·편입생 반편성고사 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [277/482] [비교과] [마포청소년문화의집] 2026년 청년 활동단(멘토·기획·모니터링 등) 모 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [278/482] [비교과] [시립강동청소년센터] 2025년 시립강동청소년센터 대학생 자원지도사 '한 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [279/482] [비교과] 강소기업채용 [26.02.11.] 강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [280/482] [수업] [채용] 2026년 SW·AI융합교육센터 계약직원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [281/482] [수업] [채용] 미래플러스대학 계약학과 행정조교 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [282/482] [취업] 인턴쉽 [성북구 공공기관] 청년인턴 모집 (~02/19) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [283/482] [장학] 2026학년도 편입생 설명회 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [284/482] [수업] [채용] 교육혁신처 학사운영팀 행정조교 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [285/482] [비교과] 2025학년도 전기(2026년 2월) 졸업대상자 명단 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [286/482] [취업] 인턴쉽 [외부채용][성북구 공공기관] 청년인턴 추가 모집 (~02/19) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [287/482] [취업] 채용정보 [추천채용 /졸업선배근무중] 하나에프엔아이(주) 부실채권 자산/ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [288/482] [장학] [한국장학재단] 2026년 제17기 사회리더 대학생 멘토링 멘티 신청 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [289/482] [수업] [채용] 한성대학교 대학원교학팀 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [290/482] [장학] 학자금대출 2026학년도 1학기 사립학교교직원연금공단 국고학자금대여 신청 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [291/482] [취업] [시립성북청소년센터] 2026년 성북청소년센터 청소년운영위원회 '마중물' → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [292/482] [수업] 2025학년도 2학기 수업평가 우수강좌 공지 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [293/482] [비교과] 2025학년도 2학기 동아리활동 평가 결과 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [294/482] [수업] 2026학년도 1학기 상상력교양대학 서면신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [295/482] [장학] [연장] 2025-2 한성 학생 CEO 발굴 프로젝트(2차) 신청 안내( → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [296/482] [취업] 인턴쉽 [외부채용][도봉구 거주 청년-공공기관 실무형 청년인턴] 6개월  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [297/482] [수업] 채용정보 [추천채용]크레신(삼성전자협력사) SW개발자 (~02/18) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [298/482] [장학] 2026-1학기 상상력인재학부 멘토링 프로그램 '상상멘토단' 모집 공고  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [299/482] [비교과] [채용] 교육혁신원 교수학습센터 학습 객원상담사 채용공고(기간 연장) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [300/482] [수업] [채용] IT인프라팀 상상관 / 탐구관 기자재실 야간조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [301/482] [비교과] 채용정보 [외부채용][한국대학교육협의회] 무기직(행정) 신규직원 채용(~ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [302/482] [수업] 채용정보 [채용] 한성대학교 학생생활상담센터 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [303/482] [수업] 2026학년도 1학기 영어 커뮤니케이션 이수 면제 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [304/482] [취업] 채용정보 [추천채용] 바로저축은행 경영기획 신입 (~02/19) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [305/482] [장학] 면학근로 2026학년도 1학기 면학근로장학생 신청 안내(2/9~2/18) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [306/482] [장학] 2026학년도 1학기 IPP 현장실습생 추가모집 안내 -3월 실습시작- → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [307/482] [장학] 학자금대출 2026년 제1차 서울시 학자금대출 이자 지원 사업 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [308/482] [비교과] 2025학년도 상상력교양대학 교강사 역량증진 동계 워크숍 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [309/482] [수업] 채용정보 [추천채용] (주)가빈(동문기업) 관리부회계(~02/19) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [310/482] [기타] 2025학년도 전기 학위수여식 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [311/482] [장학] 26년도 1학기 군 이러닝 수강안내(대학 학점취득 원격강좌 수강안내)(수 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [312/482] [비교과] [성북구] 구민참여 에너지절약 실천프로그램 「에코마일리지제(Eco Mil → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [313/482] [수업] 2026학년도 1학기 수강신청 정보 안내(수정7) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [314/482] [비교과] 강소기업채용 [26.02.04.] 강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [315/482] [취업] 채용정보 [추천채용] (주)그린파트너즈[아모레퍼시픽 자회사] _ 아모레  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [316/482] [수업] [한성대X대한상공회의소 서울기술교육센터KDT]반도체SW 채용연계과정 선착 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [317/482] [수업] 채용정보 [채용] 글로벌인재대학 교학팀 행정조교 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [318/482] [장학] 2026학년도 1학기 한성 현장실습생 추가모집 안내 (~2/6) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [319/482] [취업] 2025 진로취업멘토링 성과공유대회 입상자 발표 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [320/482] [기타] 2025 진로탐색학점제 성과공유대회 입상자 발표 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [321/482] [기타] 정전안내-2월7일 토요일 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [322/482] [수업] 채용정보 [한국산업인력공단] '26년 상반기 신규직원 채용(~2/12 1 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [323/482] [장학] [상상빌리지]2026학년도 1학기 상상빌리지(행복기숙사) 정시모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [324/482] [취업] 2026학년도 1학기 교차전부(과) 선발결과 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [325/482] [장학] 2026학년도 2학기 영어권 학기어학연수 및 1+1 프로그램 파견학생 선 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [326/482] [장학] 2026학년도 2학기 영어권 파견 교환학생 선발안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [327/482] [장학] 2025-2 한성 학생 CEO 발굴 프로젝트(2차) 신청 안내(25년 사 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [328/482] [장학] 교외장학금 2026년도 (사)세계시민포럼 가현 펠로우쉽: 대학 꿈나무 장 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [329/482] [비교과] 채용정보 [지원추천](재)동대문문화재단 일반직(정규), 기간제 모집(~0 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [330/482] [장학] 국가근로 2026학년도 1학기 국가근로장학금 학생 희망근로지 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fca05554c70>
  [331/482] [기타] [용산구시설관리공단] 2026년 용산청소년센터 ESG 서포터즈 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc99577b880>
  [332/482] [취업] [시립은평청소년센터] 2026년 은평교육협력특화지구사업 학과 탐색 전공  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [333/482] [장학] 2026학년도 1학기 학기초과자 등록금 납부 안내 → QA 2개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [334/482] [장학] 2026학년도 1학기 재학생 등록금 분할납부 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [335/482] [장학] 2026학년도 1학기 재학생 등록금 납부 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [336/482] [비교과] [총학생회] 2026 새내기 새로배움터 Career Design Camp → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [337/482] [취업] 채용정보 [추천채용] [동문기업] 센텍(주) CS(고객관리) 및 영업지원 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [338/482] [수업] 채용정보 [추천채용] 더파운더즈 _온라인경험/마케팅 디자인 3개월 인턴( → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [339/482] [장학] 2026학년도 1학기 IPP 현장실습생 추가모집 안내 -3월 실습시작- → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [340/482] [수업] [채용] 문학문화콘텐츠학과 행정조교 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [341/482] [비교과] [영자신문사 Hansung Today] 제 40기 수습기자 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [342/482] [비교과] [채용] 한성대학교 생활관(행복기숙사) 행정실 조교 모집 공고(기한 :  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [343/482] [수업] [채용]경영대학원 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc9983a44f0>
  [344/482] [기타] [남양주시] 남양주시 대학생 플래너즈 16기 정기모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [345/482] [비교과] 2026학년도 1학기 창업대체학점 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [346/482] [수업] 2026학년도 1학기 창업휴학 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [347/482] [비교과] 강소기업채용 [26.01.28.] 강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [348/482] [장학] 국가장학금 2026학년도 1학기 국가장학금 2차 신청 안내(3/17 마감 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [349/482] [비교과] [교내 선발 전형 ~01/29 15:00 마감연장 ] 2026년 지역인재 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [350/482] [수업] [총학생회] 2025학년도 전기 학위수여식 학사복 대여 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [351/482] [취업] 채용정보 [★교수님 추천채용] (주)아던트_(전공무관) IT 컨설턴트 신 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [352/482] [장학] 국가장학금 2026학년도 1학기 주거안정장학금 2차 신청 안내(3/17  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [353/482] [취업] 채용정보 [추천채용]kakaoStyle 트렌드리서처 최소3개월 인턴(~채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc98cd10cc0>
  [354/482] [취업] [한국관광공사] 2026 대한민국 구석구석 대학생 기자단 트래블리더 18 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [355/482] [비교과] [대플] 2025학년도 전기 학위수여식 프로그램 「나 이제 취업할래!」안 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [356/482] [취업] 채용정보 [추천채용] 토스(toss)쇼핑_ 11기 Merchandisin → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [357/482] [수업] 2026학년도 1학기 수강신청 장바구니 시행 안내(수정10) → QA 2개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [358/482] [취업] [한성대학교] 2026학년도 상반기 시설관리직(미화) 채용공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [359/482] [수업] [한성대학교] 2026학년도 상반기 신규직(특수직) 채용공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [360/482] [비교과] [한성대학교] 2026학년도 상반기 신규직(일반기술직) 채용공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [361/482] [장학] 2026학년도 2학기 일어권 파견 교환학생 선발안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [362/482] [수업] 한성대학교 언어교육센터 한국어과정 강사 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc998328c20>
  [363/482] [기타] [도봉동청소년문화의집] 2026년 청년 서포터즈단 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fca063e0ef0>
  [364/482] [비교과] 2026 '대학생진로멘토단 DA:ON' 대학생 멘토 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [365/482] [장학] 2026학년도 1학기 휴·복학 신청 안내(2.2.~2.27.) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [366/482] [수업] 2026학년도 1학기 제3트랙 이수신청 안내(2.2.~2.6.) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [367/482] [수업] 2026학년도 1학기 제3트랙 이수신청 안내 (2.2.~2.6.) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [368/482] [수업] 2026학년도 1학기 복수·부전공 신청 및 변경신청 안내 (2.2.~2. → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [369/482] [비교과] [비교과5pt, 선착순!!] 2025학년도 마음건강 자가진단 셀프케어 프 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [370/482] [장학] RISE-up 취·창업 성과사례 수기 공모(멘토링) 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fca1c1158f0>
  [371/482] [기타] 용산구청소년상담복지센터 및 용산구청소년지원센터 꿈드림 멘토 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [372/482] [비교과] 2026년 취업 미리보기_산업(일하는 분야)별 성공전략 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fca8907b7e0>
  [373/482] [기타] [(재)광명시청소년재단] 2026년 광명시청소년진로진학지원센터 대학생 멘 → QA 3개

Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats
Could not get FontBBox from font descriptor because None cannot be parsed as 4 floats

  [374/482] [장학] 채용정보 [★교수님 추천채용5.] 웅진IT_총3개 직무(채용연계형인턴)( → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [375/482] [수업] [채용] 상상력교양대학 기초교양학부 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [376/482] [장학] 교외장학금 2026학년도 1학기 (재)연재장학재단 31기 장학생 선발 안 → QA 3개
    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc98c6f8cc0>
    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc98c6fb6f0>

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc98c6fa250>
  [377/482] [비교과] [시립마포청소년센터] 2026년 청소년 참여활동단(청소년운영위원회·대학생 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [378/482] [취업] [국내] 2026-1학기 ICT인턴십 프로젝트 인턴십 참가자 모집(~1/ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [379/482] [수업] [마감] 한성대학교 우체국 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [380/482] [수업] 2025학년도 전기(2026.2) 졸업사정 결과 조회 및 이상유무 입력  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [381/482] [장학] [채용] 교육혁신처 학사운영팀 임시직 채용 공고(대학혁신지원사업) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [382/482] [장학] 교외장학금 2026년 현대차그룹 대학생 교육봉사단 현대점프스쿨 13기 대 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [383/482] [비교과] 강소기업채용 [26.01.21.] 강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [384/482] [취업] 채용정보 [★교수님 추천채용5.](주)타임게이트_미들웨어/네트워크 엔지니 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [385/482] [장학] [에피소드] 2026학년도 1학기 외부 임차기숙사 입사생 모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [386/482] [수업] 채용정보 [IPP교수님 추천] (주)오픈와이드 리눅스,서버스토리 엔지니어 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [387/482] [취업] [한성대학교x로보시지 주관] 제1회 Physical AI 해커톤 개최 참 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [388/482] [장학] 2026학년도 1학기 말레이시아 학기어학연수 파견학생 선발안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [389/482] [장학] 2026학년도 1학기 진로탐색학점제 설명회(학점인정) 신청자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [390/482] [기타] [교육혁신지원센터] 2025학년도 전공교육과정 모듈화 워크숍 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [391/482] [장학] 2026학년도 1학기 현장실습생 모집 안내(3월 실습시작) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [392/482] [장학] Stay & Study in school 장학사업 2026학년도 1학기  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [393/482] [비교과] 2025학년도 동계 글로벌 플레이랩(Global PlayLab) 참가자  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [394/482] [기타] 2025학년도 동계 라이프 디자인 스쿨 우수 과제물 발표 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [395/482] [장학] [한성대신문사] 제60기 수습기자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [396/482] [수업] [채용] 사회과학부 부동산학과 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [397/482] [수업] 2026학년도 Micro Degree(MD) 현장심화형 이수 신청 연장  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [398/482] [비교과] [RISE사업추진센터] 서울RISE사업 2026년 예비창업가 아카데미 참 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [399/482] [수업] [채용 연장] 한성대학교 캠퍼스타운창업센터 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [400/482] [장학] <[KT커머스] 2026학년도 1학기(3월 실습시작) IPP현장실습생 모 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [401/482] [취업] 채용정보 [종료][★교수님 추천채용.1] (주)아던트_(전공무관) IT  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [402/482] [수업] [우촌학사] 2026학년도 1학기 생활관 입주자 모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc997ad92b0>
  [403/482] [비교과] [부평구청소년수련관] 2026 부평구청소년수련관 15기 대학생서포터즈 모 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [404/482] [수업] [채용] 2026년 SW중심대학사업단 계약직원 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [405/482] [수업] 채용정보 [추천채용] (주)가빈(동문재직기업) 관리부회계(~01/22) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [406/482] [비교과] [고양시자원봉사센터] 2026 청소년・청년 자원봉사 기획단 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [407/482] [수업] 노원교육플랫폼 대학생 학습멘토링 멘토 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [408/482] [비교과] [인턴IN메타 8기 프로그램 참여자 모집 안내] ~ 2/1까지(앱 가입  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [409/482] [비교과] 채용정보 [추천채용]자라리테일코리아 (패션디자인전공 교수추천시 서류 면제 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [410/482] [비교과] [SW중심] 2026년도 SW마에스트로 과정 제16기 연수생 모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [411/482] [비교과] 강소기업채용 [26.01.14.] 강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [412/482] [장학] 국가근로 2026학년도 1학기 국가근로장학금 2차 학생 신청기간 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [413/482] [비교과] 2026 신입생 오리엔테이션 행사 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [414/482] [수업] [마감]2026학년도 1학기 한성대학교 비전임교원 및 강사 공개채용 안내 → QA 2개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [415/482] [취업] 학교기업 케이키친 한상 포장전용 메뉴 할인 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [416/482] [장학] 2025학년도 겨울계절학기 성적조회 및 성적이의신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [417/482] [비교과] 2025학년도 동계 글로벌 플레이랩(Global PlayLab) 참가자  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [418/482] [장학] [시립성북청소년센터] 2026년 성북청소년센터 대학생 멘토링단 '멘토스' → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [419/482] [장학] 교외장학금 2026년 (재)은평구민장학재단 지역사회기여 장학생 선발 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [420/482] [비교과] [RISE사업추진센터] 서울RISE사업 2026년 예비창업가 아카데미 참 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [421/482] [비교과] [RISE사업추진센터] 서울RISE사업 2026년 예비창업가 아카데미 참 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [422/482] [비교과] [RISE사업추진센터] 서울RISE사업 2026년 예비창업가 아카데미 참 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [423/482] [비교과] [RISE사업추진센터] 서울RISE사업 2026년 예비창업가 아카데미 참 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [424/482] [비교과] [RISE사업추진센터] 서울RISE사업 2026년 예비창업가 아카데미 참 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [425/482] [비교과] [RISE사업추진센터] 서울RISE사업 2026년 예비창업가 아카데미 참 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [426/482] [기타] [교양영어과정] 2026학년도 1차 재학생 영어커뮤니케이션 반편성고사 접 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [427/482] [비교과] 2026학년도 예비대학 프로그램 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [428/482] [수업] [채용] 한성대학교 우체국 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [429/482] [수업] 채용정보 [추천채용] (주)파트론(삼성전자협력사)_기구설계 신입(~1/1 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [430/482] [수업] 2026학년도 1학기 트랙변경 신청 안내(1.19.~1.23.) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [431/482] [수업] [채용] 한성대학교 캠퍼스타운창업센터 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [432/482] [수업] 2026학년도 1학기 학점교류 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [433/482] [수업] 2026학년도 1학기 학점교류 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [434/482] [수업] 2026학년도 1학기 학점교류 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [435/482] [수업] 2026학년도 1학기 학점교류 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [436/482] [수업] 2026학년도 1학기 학점교류 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [437/482] [수업] 2026학년도 1학기 학점교류 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [438/482] [수업] [채용] 예산관리팀 행정조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [439/482] [비교과] [RISE사업추진센터]서울RISE사업 중국 베이징대 글로벌 창업교육 프로 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [440/482] [장학] 채용정보 [★교수님 추천채용](주)한컴위드 _ 총무 계약직(연장~01/1 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [441/482] [취업] 채용정보 [★교수님 추천채용](주)오픈베이스 _재경팀 (계약)신입 (~0 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [442/482] [장학] 채용정보 [추천채용]송월타올 서울지사 _리테일영업관리 신입(~1/18) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [443/482] [장학] [채용] 한성대학교 IPP사업단 임시직 채용 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [444/482] [비교과] 2025 비교과 이수자 추천 프로그램 수상작 모음 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [445/482] [기타] 청소년 정서진로 멘토링 [씨드스쿨] 대학생 봉사자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [446/482] [수업] 2025학년도 전기(2026년 2월) 학사학위취득 유예신청 취소신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [447/482] [수업] 채용정보 [추천채용]스킨이데아_ 상품기획/마케팅기획/국내영업/해외영업 전 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [448/482] [장학] 학자금대출 2026년 상반기 울산광역시 대학(원)생 학자금대출 이자지원사 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [449/482] [비교과] [비교과 5pt(해석상담시)] 2025-겨울방학 심리검사 패키지☃️ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [450/482] [장학] 진로탐색학점제 성과공유대회 - 장학금 지급 (2025학년도 진로탐색학점제 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [451/482] [비교과] 강소기업채용 [26.01.07] 강소 및 교내 추천채용 리스트 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [452/482] [장학] [사단법인 점프] 2026 JUMP ON 멘토링 여성 대학생 교육봉사자  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [453/482] [장학] 교외장학금 2026학년도 (재)우양재단 마루·나래·다솜 신규장학생 선발  → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [454/482] [수업] 2026학년도 1학기 교차전부(과) 선발 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [455/482] [수업] 선택 트랙 간 상호(제1트랙⇄제2트랙) 전공과목 변경신청 추가시행 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [456/482] [수업] 2025학년도 전기(2026년 2월) 졸업예정자 다전공 이수구분 변경 신 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [457/482] [수업] 2025학년도 전기(2026년 2월) 졸업예정자 교육과정변경으로 인한 이 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [458/482] [수업] 채용정보 [추천채용] 대한경제신문사 신입 기자(~01/18) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [459/482] [장학] 교외장학금 2026학년도 (재)심명문화재단 장학생 선발 안내(2/2~2/ → QA 2개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [460/482] [기타] 2027 충청 유니버시아드대회 대학생 서포터즈 「제3기 2027유니크루」 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [461/482] [기타] [중랑청소년센터] 2026년 뚝딱이 창의공작소 대학생 메이커 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc997803f10>
  [462/482] [기타] 2026년 상반기 국립중앙박물관 청년멘토 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [463/482] [장학] 학자금대출 2026년 1학기 농촌출신대학(원)생 학자금대출 신청 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc998372840>
  [464/482] [장학] [ESG센터] 2026년 서울런 멘토단 참여 대학생 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

    ⚠️ OCR 실패 (https://intra.hansung.ac.kr/workflow/fileReadImage): cannot identify image file <_io.BytesIO object at 0x7fc98b677bf0>
  [465/482] [비교과] JA Korea 대학생경제교육봉사단 UJAT 36기 대학생 참여자 모집 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [466/482] [수업] 2026학년도 연계전공 신청 접수 연장 안내 (~1/11) → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [467/482] [취업] 채용정보 [추천채용]오뚜기물류서비스(주) 물류운영관리(남양주센터근무)(~ → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [468/482] [비교과] 인턴쉽 [추천KDT](주)메타넷디지털(주)_ Applied AIE Jum → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [469/482] [비교과] [한성대학교 방송국 HBS] 제49기 수습국원 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [470/482] [장학] 학자금대출 2026년 상반기 경기도 대학생 학자금 대출이자 지원 안내(2 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [471/482] [수업] [채용] IT인프라팀 상상관 / 탐구관 기자재실 조교 모집 공고 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [472/482] [기타] [안 내] 낙산관 체력단련실 샤워장 바닥 방수공사 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [473/482] [비교과] [채용] 한성대학교 지역평생교육지원단 평생교육통합지원센터 교육연구교수 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [474/482] [비교과] [채용] 한성대학교 지역평생교육지원단 평생교육통합지원센터 교육연구교수 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [475/482] [비교과] [채용] 한성대학교 지역평생교육지원단 평생교육통합지원센터 교육연구교수 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [476/482] [비교과] [채용] 한성대학교 지역평생교육지원단 평생교육통합지원센터 교육연구교수 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [477/482] [비교과] [채용] 한성대학교 지역평생교육지원단 평생교육통합지원센터 교육연구교수 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [478/482] [비교과] [채용] 한성대학교 지역평생교육지원단 평생교육통합지원센터 교육연구교수 채 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [479/482] [비교과] [비교과 30pt] TCI를 활용한 자기이해 기반 진로탐색 집단 워크샵 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [480/482] [장학] [교육혁신지원센터]2025학년도 대학생 핵심역량진단검사(K-CESA)참여 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [481/482] [장학] [상상빌리지] 2026년도 1학기 상상빌리지(행복기숙사) 정규모집 안내 → QA 3개

Both `max_new_tokens` (=80) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  [482/482] [수업] Micro Degree(현장심화형) 과정 이수신청 기간 연장 안내 (~1 → QA 3개

✅ 공지 캐시 저장: ./data/notices_cache.json (482건)
✅ QA 저장: ./data/synthetic_qa.json (1432쌍)

In [ ]:
# 퀜 모델 캐시 푸는걸로 추정
del qwen
import gc, torch; gc.collect(); torch.cuda.empty_cache()

NameError: name 'notices' is not defined

In [ ]:
# 본격 파인튜닝 시작. 실행하기 전 data 폴더에 파일 있는지 확인 요망.
notices = load_notices_cache()
finetune_all(notices)

🚀 전체 파인튜닝 시작 (메모리 절약 모드)
  공지 482건 로드됨
  ♻️  기존 QA 재사용

=======================================================
🔧 [1/2] 임베딩 모델 파인튜닝 시작
=======================================================
  ♻️  기존 QA 재사용 — 1432쌍 (crawl_all 시 생성된 것)
  Synthetic QA 1432쌍 준비 완료

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 26663.25it/s]
RobertaModel LOAD REPORT from: jhgan/ko-sroberta-multitask
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.05s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.05s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.74s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.86s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.92s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.86s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.02s/it]

✅ 임베딩 모델 저장: ./models/embed_finetuned

  🧹 임베딩 메모리 해제 완료
  RAM 여유 확보 후 분류 모델 시작

=======================================================
🔧 [2/2] 분류 모델 파인튜닝 시작
=======================================================
  학습 데이터 482건

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6320.45it/s]
BertForSequenceClassification LOAD REPORT from: klue/bert-base
Key                                        | Status     |
-------------------------------------------+------------+-
bert.embeddings.position_ids               | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100%|██████████| 433/433 [00:00<00:00, 5075.54 examples/s]
Map: 100%|██████████| 49/49 [00:00<00:00, 2981.72 examples/s]

Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.83s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it]
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.90s/it]
There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].
Writing model shards: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it]

✅ 분류 모델 저장: ./models/classify_finetuned

  🧹 분류 메모리 해제 완료

🎉 전체 파인튜닝 완료!
  → save_models() 로 Drive에 저장하세요.

In [ ]:
#베이스 모델과 파인튜닝 모델 비교
evaluate_embedding(notices)

📊 [베이스 모델] 평가 중...

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 12664.50it/s]
RobertaModel LOAD REPORT from: jhgan/ko-sroberta-multitask
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|██████████| 15/15 [00:01<00:00, 13.87it/s]
Batches: 100%|██████████| 45/45 [00:00<00:00, 63.00it/s]

  결과: {'Recall@1': 0.2493, 'Recall@3': 0.3534, 'Recall@5': 0.4008, 'Recall@10': 0.4623, 'MRR': np.float64(0.3259)}

📊 [파인튜닝 모델] 평가 중...

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 10102.96it/s]
Batches: 100%|██████████| 15/15 [00:01<00:00, 13.74it/s]
Batches: 100%|██████████| 45/45 [00:00<00:00, 62.79it/s]

  결과: {'Recall@1': 0.6837, 'Recall@3': 0.8694, 'Recall@5': 0.9134, 'Recall@10': 0.9735, 'MRR': np.float64(0.7873)}

=======================================================
📈 파인튜닝 전후 비교
=======================================================
지표             베이스 모델              파인튜닝 모델
-------------------------------------------------------
Recall@1       0.2493              0.6837
Recall@3       0.3534              0.8694
Recall@5       0.4008              0.9134
Recall@10      0.4623              0.9735
MRR            0.3259              0.7873

{'베이스 모델': {'Recall@1': 0.2493,
  'Recall@3': 0.3534,
  'Recall@5': 0.4008,
  'Recall@10': 0.4623,
  'MRR': np.float64(0.3259)},
 '파인튜닝 모델': {'Recall@1': 0.6837,
  'Recall@3': 0.8694,
  'Recall@5': 0.9134,
  'Recall@10': 0.9735,
  'MRR': np.float64(0.7873)}}

In [ ]:
# 만약에 오늘 작업한걸 zip으로 저장하고 싶다면 zip 설치하세요.
!sudo apt-get update && sudo apt-get install -y zip

Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3844 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1622 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7125 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4219 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1310 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6803 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [84.0 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.6 kB]
Fetched 25.6 MB in 4s (5776 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  zip
0 upgraded, 1 newly installed, 0 to remove and 117 not upgraded.
Need to get 176 kB of archives.
After this operation, 544 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 zip amd64 3.0-12build2 [176 kB]
Fetched 176 kB in 1s (119 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package zip.
(Reading database ... 24850 files and directories currently installed.)
Preparing to unpack .../zip_3.0-12build2_amd64.deb ...
Unpacking zip (3.0-12build2) ...
Setting up zip (3.0-12build2) ...

In [ ]:
#그리고 이거 실행하세요. 파일명, 압축할 폴더 경로 순서임.
!zip -r 0407.zip 0407

  adding: 0407/ (stored 0%)
  adding: 0407/Untitled.ipynb (deflated 92%)
  adding: 0407/models/ (stored 0%)
  adding: 0407/models/embed_finetuned/ (stored 0%)
  adding: 0407/models/embed_finetuned/tokenizer.json (deflated 69%)
  adding: 0407/models/embed_finetuned/eval/ (stored 0%)
  adding: 0407/models/embed_finetuned/eval/Information-Retrieval_evaluation_hansung_qa_results.csv (deflated 88%)
  adding: 0407/models/embed_finetuned/modules.json (deflated 53%)
  adding: 0407/models/embed_finetuned/tokenizer_config.json (deflated 55%)
  adding: 0407/models/embed_finetuned/config.json (deflated 52%)
  adding: 0407/models/embed_finetuned/README.md (deflated 64%)
  adding: 0407/models/embed_finetuned/config_sentence_transformers.json (deflated 41%)
  adding: 0407/models/embed_finetuned/sentence_bert_config.json (deflated 9%)
  adding: 0407/models/embed_finetuned/model.safetensors (deflated 8%)
  adding: 0407/models/embed_finetuned/1_Pooling/ (stored 0%)
  adding: 0407/models/embed_finetuned/1_Pooling/config.json (deflated 59%)
  adding: 0407/models/classify_finetuned/ (stored 0%)
  adding: 0407/models/classify_finetuned/tokenizer.json (deflated 69%)
  adding: 0407/models/classify_finetuned/checkpoint-252/ (stored 0%)
  adding: 0407/models/classify_finetuned/checkpoint-252/tokenizer.json (deflated 69%)
  adding: 0407/models/classify_finetuned/checkpoint-252/tokenizer_config.json (deflated 45%)
  adding: 0407/models/classify_finetuned/checkpoint-252/config.json (deflated 55%)
  adding: 0407/models/classify_finetuned/checkpoint-252/scheduler.pt (deflated 56%)
  adding: 0407/models/classify_finetuned/checkpoint-252/trainer_state.json (deflated 79%)
  adding: 0407/models/classify_finetuned/checkpoint-252/rng_state.pth (deflated 25%)
  adding: 0407/models/classify_finetuned/checkpoint-252/training_args.bin (deflated 51%)
  adding: 0407/models/classify_finetuned/checkpoint-252/optimizer.pt (deflated 26%)
  adding: 0407/models/classify_finetuned/checkpoint-252/model.safetensors